version: '3.7'

services:

  mc-authentication_db:
    container_name: mc-authentication_db
    image: postgres:12
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - mc-authentication-db:/var/lib/postgresql
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql

volumes:
  mc-authentication-db:

networks:
  mc-network:
    driver: bridge
