name: Run tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start docker containers
        run: |
          docker-compose -f docker-compose-ci.yml up --build --detach
          sleep 10  # wait for database to be ready          

      - name: Run backend unit tests
        run: docker exec -it mc-authentication-service-test ./mvnw test -Punittest -Dspring.profiles.active=ci

      - name: Run backend integration tests
        run: docker exec -it mc-authentication-service-test ./mvnw test -Pintegrationtest -Dspring.profiles.active=ci
